import { useCallback, useEffect, useMemo, useRef, useState, type CSSProperties } from "react";
import { api, eventUrl } from "@/lib/api";
import type { DiscussionDto, DiscussionErrorEvent, DiscussionFinishedEvent, DiscussionListItemDto, DiscussionStatus, DiscussionSnapshotEvent, InsightsUpdatedEvent, ParticipantDto, ParticipantStatusChangedEvent, UtteranceCreatedEvent } from "@/types/contracts";

type Route = { kind: "home" } | { kind: "create" } | { kind: "discussion"; id: string };
type ConnectionState = "connecting" | "connected" | "reconnecting";
const labels: Record<DiscussionStatus, string> = { DRAFT: "草稿", CAST_READY: "待开始", RUNNING: "直播中", FINISHED: "已结束", FAILED: "运行异常" };
const Icon = ({ children }: { children: string }) => <span aria-hidden="true">{children}</span>;

function parseRoute(pathname: string): Route { if (pathname === "/create") return { kind: "create" }; const match = pathname.match(/^\/discussions\/([^/]+)$/); return match ? { kind: "discussion", id: decodeURIComponent(match[1]) } : { kind: "home" }; }
function Status({ value }: { value: DiscussionStatus }) { return <span className={`status ${value.toLowerCase()}`}><i />{labels[value]}</span>; }

function Header({ route, discussion, navigate }: { route: Route; discussion: DiscussionDto | null; navigate: (path: string) => void }) {
  const title = route.kind === "home" ? "讨论现场" : route.kind === "create" ? "发起一场讨论" : discussion?.topic ?? "讨论详情";
  return <header className="app-header"><button className="brand" onClick={() => navigate("/")}>AI Panel Studio</button><p title={title}>{title}</p><button className="button primary" onClick={() => navigate("/create")}><Icon>＋</Icon>发起讨论</button></header>;
}

function Home({ navigate }: { navigate: (path: string) => void }) {
  const [items, setItems] = useState<DiscussionListItemDto[]>([]); const [error, setError] = useState<string | null>(null); const [reloadKey, setReloadKey] = useState(0);
  useEffect(() => { const controller = new AbortController(); setError(null); api.listDiscussions(controller.signal).then((response) => setItems(response.items)).catch((reason: unknown) => { if (!(reason instanceof DOMException && reason.name === "AbortError")) setError(reason instanceof Error ? reason.message : "讨论列表加载失败。"); }); return () => controller.abort(); }, [reloadKey]);
  return <main className="page home"><section className="hero"><small>AI ROUND TABLE · LIVE VIEW</small><h1>让每一个重要问题，<br />都拥有一场值得观看的讨论。</h1><p>邀请不同立场的 AI 专家，在清晰、可追踪的现场中共同拆解一个问题。</p><button className="button primary large" onClick={() => navigate("/create")}>发起一场讨论 <Icon>→</Icon></button></section><section><div className="section-title"><div><small>DISCUSSIONS</small><h2>正在发生的讨论</h2></div><span>共 {items.length} 场</span></div>{error ? <div className="inline-feedback" role="alert"><p>{error}</p><button className="button quiet" onClick={() => setReloadKey((key) => key + 1)}>重新加载</button></div> : null}{!error && items.length === 0 ? <div className="empty-state"><h3>还没有讨论现场</h3><p>从一个值得讨论的问题开始，邀请 AI 专家共同拆解。</p><button className="button primary" onClick={() => navigate("/create")}>发起第一场讨论 <Icon>→</Icon></button></div> : null}<div className="discussion-grid">{items.map((item) => <article className="discussion-card discussion-link" key={item.id} role="link" tabIndex={0} onClick={() => navigate(`/discussions/${item.id}`)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); navigate(`/discussions/${item.id}`); } }}><div><Status value={item.status} /><span>{item.participant_count} 位参与者</span></div><h3>{item.topic}</h3><p>最近更新于 {new Date(item.updated_at).toLocaleString()}</p><span className="text-button">{item.status === "CAST_READY" || item.status === "DRAFT" ? "查看阵容" : "查看讨论"} <Icon>→</Icon></span></article>)}</div></section></main>;
}

function Create({ navigate }: { navigate: (path: string) => void }) {
  const [topic, setTopic] = useState(""); const [count, setCount] = useState(4); const [tried, setTried] = useState(false); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState<string | null>(null);
  const submit = async () => { setTried(true); if (!topic.trim()) return; setSubmitting(true); setError(null); try { const discussion = await api.createDiscussion(topic, count); navigate(`/discussions/${discussion.id}`); } catch (reason) { setError(reason instanceof Error ? reason.message : "创建讨论失败。"); } finally { setSubmitting(false); } };
  return <main className="page form-page"><section className="form-card"><small>NEW DISCUSSION</small><h1>从一个值得讨论的问题开始。</h1><p>我们会为你生成一位主持人与 {count} 位立场互补的专家。</p><label htmlFor="topic">讨论话题 <em>必填</em></label><textarea id="topic" value={topic} aria-invalid={tried && !topic.trim()} onBlur={() => setTried(true)} onChange={(event) => setTopic(event.target.value)} />{tried && !topic.trim() ? <b className="error">请输入一个讨论话题。</b> : null}{error ? <b className="error">{error}</b> : null}<div className="expert-row"><div><label>专家人数</label><p>不含主持人，可选择 2–8 名。</p></div><div className="stepper"><button disabled={count === 2 || submitting} onClick={() => setCount(count - 1)} aria-label="减少专家人数">−</button><strong>{count}</strong><button disabled={count === 8 || submitting} onClick={() => setCount(count + 1)} aria-label="增加专家人数">＋</button></div></div><button className="button primary wide" disabled={submitting} onClick={submit}>{submitting ? "正在创建…" : "创建讨论"} <Icon>→</Icon></button></section></main>;
}

function PersonCard({ person, showStatus = false }: { person: ParticipantDto; showStatus?: boolean }) {
  const state = { idle: "待机", preparing: "准备发言", speaking: "发言中" }[person.runtime_status]; const active = person.runtime_status !== "idle";
  return <article className={`person ${showStatus ? person.runtime_status : ""}`} style={{ "--person": person.color } as CSSProperties}><div className="person-top"><span className="avatar">{person.name[0]}</span><div><small>{person.role === "moderator" ? "主持人" : "专家"}</small><h3>{person.name}</h3><p className="person-title">{person.title}</p><p className="person-detail">{person.profession}</p></div>{showStatus ? <span className="runtime"><i />{state}</span> : null}</div><p className={showStatus ? "focus" : "stance"}>{showStatus ? <><small>{active ? "公开关注点" : "嘉宾立场"}</small>{active ? person.public_focus ?? "等待讨论推进" : `${person.profession} · ${person.stance}`}</> : person.stance}</p></article>;
}

function Cast({ discussion, onGenerate, onConfirm, pending, error }: { discussion: DiscussionDto; onGenerate: () => Promise<void>; onConfirm: () => Promise<void>; pending: boolean; error: string | null }) {
  const moderator = discussion.participants.find((person) => person.role === "moderator"); const experts = discussion.participants.filter((person) => person.role === "expert"); const hasCast = discussion.participants.length > 0;
  return <main className="page cast"><section className="cast-heading"><div><small>{hasCast ? "CAST READY · 01" : "DRAFT · 01"}</small><h1>{discussion.topic}</h1></div><aside><b>{hasCast ? "嘉宾阵容已就绪" : "等待生成嘉宾阵容"}</b><span>{hasCast ? `1 位主持人 · ${discussion.expert_count} 位专家` : `将生成 1 位主持人与 ${discussion.expert_count} 位专家`}</span><p>确认后，讨论将在演播厅中显式开始。</p></aside></section>{error ? <p className="error">{error}</p> : null}{hasCast ? <section className="cast-roster"><div className="roster-label"><span>节目主持</span><i>01</i></div>{moderator ? <div className="moderator"><PersonCard person={moderator} /></div> : null}<div className="roster-label"><span>圆桌嘉宾</span><i>{String(experts.length).padStart(2, "0")}</i></div><div className="cast-grid">{experts.map((person, index) => <div className="expert-slot" key={person.id}><span>{String(index + 1).padStart(2, "0")}</span><PersonCard person={person} /></div>)}</div></section> : null}<div className="action-bar"><p><b>{hasCast ? `${discussion.participants.length} 位嘉宾已就绪` : "尚未生成阵容"}</b><span>生成后可检查并确认阵容。</span></p><div>{hasCast ? <><button className="button quiet" disabled={pending} onClick={() => void onGenerate()}>重新生成</button><button className="button primary" disabled={pending} onClick={() => void onConfirm()}>{pending ? "正在确认…" : "确认阵容"} <Icon>→</Icon></button></> : <button className="button primary" disabled={pending} onClick={() => void onGenerate()}>{pending ? "正在生成…" : "生成 AI 阵容"}</button>}</div></div></main>;
}

function Transcript({ discussion }: { discussion: DiscussionDto }) {
  const box = useRef<HTMLDivElement>(null); const previousLength = useRef(0); const [paused, setPaused] = useState(false); const [newCount, setNewCount] = useState(0); const utterances = useMemo(() => [...discussion.utterances].sort((left, right) => left.sequence - right.sequence), [discussion.utterances]);
  useEffect(() => { const added = Math.max(0, utterances.length - previousLength.current); previousLength.current = utterances.length; if (paused && added) setNewCount((count) => count + added); if (!paused) box.current?.scrollTo({ top: box.current.scrollHeight }); }, [utterances.length, paused]);
  const scroll = () => { const node = box.current; if (node) setPaused(node.scrollHeight - node.scrollTop - node.clientHeight > 80); }; const latest = () => { box.current?.scrollTo({ top: box.current.scrollHeight, behavior: "smooth" }); setPaused(false); setNewCount(0); };
  return <section className="panel transcript"><header><div><small>LIVE TRANSCRIPT</small><h2>现场 Transcript</h2></div><span>{utterances.length} / {discussion.max_public_utterances} 条公开发言</span></header><div className="transcript-scroll" ref={box} onScroll={scroll} aria-live="polite">{utterances.length === 0 && discussion.status === "RUNNING" ? <p className="transcript-empty">主持人正在开场…</p> : null}{utterances.map((utterance) => { const speaker = discussion.participants.find((person) => person.id === utterance.participant_id); return speaker ? <article className="utterance" key={utterance.id} style={{ "--person": speaker.color } as CSSProperties}><div><strong>{speaker.name}</strong><span>{speaker.profession} · {speaker.title}</span><time>刚刚</time></div><p>{utterance.content}</p></article> : null; })}</div>{paused && newCount > 0 ? <button className="new-message" onClick={latest}>有 {newCount} 条新发言 <Icon>↓</Icon></button> : null}</section>;
}

function Insights({ discussion }: { discussion: DiscussionDto }) {
  const active = discussion.insights.filter((insight) => insight.active); const groups = [{ type: "consensus", title: "已形成共识", empty: "共识正在形成" }, { type: "disagreement", title: "关键分歧", empty: "分歧尚未显现" }] as const;
  return <section className="insights" aria-label="观点面板" aria-live="polite">{groups.map((group) => { const entries = active.filter((insight) => insight.type === group.type); return <article className={`insight ${group.type}`} key={group.type}><h2>{group.title}</h2>{entries.length ? <ul>{entries.map((insight) => <li key={insight.id}>{insight.content}</li>)}</ul> : <p>{group.empty}</p>}</article>; })}</section>;
}

function Connection({ state }: { state: ConnectionState }) { return <span className={`connection ${state}`}><i />{state === "connected" ? "实时连接" : "正在连接"}</span>; }

function StageGuest({ person }: { person: ParticipantDto }) {
  const active = person.runtime_status !== "idle";
  const state = { idle: "待机", preparing: "准备发言", speaking: "发言中" }[person.runtime_status];
  const label = active ? "公开关注点" : "嘉宾立场";
  const detail = active ? person.public_focus ?? "等待讨论推进" : person.stance;
  return <article className={`person stage-guest ${person.runtime_status}`} style={{ "--person": person.color } as CSSProperties}>
    <div className="stage-guest-trigger">
      <span className="avatar">{person.name[0]}</span><span><small>{person.role === "moderator" ? "主持人" : "专家"}</small><strong>{person.name}</strong><span className="person-title">{person.title}</span><span className="runtime"><i />{state}</span></span>
    </div>
    <p className="stage-stance"><small>{label}</small>{detail}</p>
  </article>;
}

function StudioHeader({ discussion, connection, pending, onStart, onStop }: { discussion: DiscussionDto; connection: ConnectionState; pending: boolean; onStart: () => Promise<void>; onStop: () => Promise<void> }) {
  const ready = discussion.status === "CAST_READY" && discussion.cast_confirmed;
  const running = discussion.status === "RUNNING";
  return <section className="studio-top"><div><p><Status value={discussion.status} /><Connection state={connection} /></p><h1>{discussion.topic}</h1></div>{ready ? <button className="button primary" disabled={pending} onClick={() => void onStart()}>{pending ? "正在开始…" : "开始讨论"} <Icon>→</Icon></button> : null}{running ? <button className="button danger" disabled={pending} onClick={() => void onStop()}>{pending ? "正在停止…" : "停止讨论"}</button> : null}</section>;
}

function GuestRail({ participants }: { participants: ParticipantDto[] }) {
  return <section className="stage-guests" aria-label="嘉宾席，可横向滚动查看所有嘉宾"><div className="stage-rail"><div className="stage-track">{participants.map((person) => <StageGuest key={person.id} person={person} />)}</div></div></section>;
}

function SummaryCard({ discussion, pending, onRetry }: { discussion: DiscussionDto; pending: boolean; onRetry: () => Promise<void> }) {
  const running = discussion.status === "RUNNING";
  const generating = discussion.status === "FINISHED" && discussion.summary_status === "pending";
  const retryable = discussion.status === "FINISHED" && discussion.summary_status === "fallback";
  return <section className="summary"><small>{running ? "IN PROGRESS" : "SUMMARY"}</small><h2>{running ? "讨论仍在推进" : generating ? "正在生成总结…" : discussion.summary_status === "fallback" ? "总结暂不可用" : "讨论总结"}</h2><p>{running ? "主持人将在观点收束后，给出自然语言总结。" : generating ? "正在独立生成讨论总结，请稍候。" : discussion.summary ?? "总结正在生成。"}</p>{retryable ? <button className="button quiet" disabled={pending} onClick={() => void onRetry()}>{pending ? "正在重试…" : "重试总结"}</button> : null}</section>;
}

function Studio({ discussion, connection, onStart, onStop, onRetry, pending, error }: { discussion: DiscussionDto; connection: ConnectionState; onStart: () => Promise<void>; onStop: () => Promise<void>; onRetry: () => Promise<void>; pending: boolean; error: string | null }) {
  const stage = [...discussion.participants].sort((left, right) => Number(right.role === "moderator") - Number(left.role === "moderator"));
  return <main className="studio"><StudioHeader discussion={discussion} connection={connection} pending={pending} onStart={onStart} onStop={onStop} />{error ? <p className="error">{error}</p> : null}<GuestRail participants={stage} /><section className="studio-content"><Transcript discussion={discussion} /><Insights discussion={discussion} /><SummaryCard discussion={discussion} pending={pending} onRetry={onRetry} /></section></main>;
}

function DiscussionPage({ id, navigate, reportDiscussion }: { id: string; navigate: (path: string) => void; reportDiscussion: (discussion: DiscussionDto | null) => void }) {
  const [discussion, setDiscussion] = useState<DiscussionDto | null>(null); const [error, setError] = useState<string | null>(null); const [pending, setPending] = useState(false); const [connection, setConnection] = useState<ConnectionState>("connecting");
  useEffect(() => { let current = true; const controller = new AbortController(); let source: EventSource | null = null; const apply = (updater: (previous: DiscussionDto) => DiscussionDto) => setDiscussion((previous) => previous?.id === id ? updater(previous) : previous); const parse = <T,>(event: MessageEvent<string>): T | null => { try { return JSON.parse(event.data) as T; } catch { return null; } }; const listen = () => { source = new EventSource(eventUrl(id)); source.addEventListener("discussion.snapshot", (event) => { const payload = parse<DiscussionSnapshotEvent>(event as MessageEvent<string>); if (current && payload?.discussion_id === id) { setDiscussion(payload.discussion); setConnection("connected"); } }); source.addEventListener("participant.status.changed", (event) => { const payload = parse<ParticipantStatusChangedEvent>(event as MessageEvent<string>); if (current && payload?.discussion_id === id) apply((previous) => ({ ...previous, participants: previous.participants.map((person) => person.id === payload.participant.id ? { ...person, ...payload.participant } : person) })); }); source.addEventListener("utterance.created", (event) => { const payload = parse<UtteranceCreatedEvent>(event as MessageEvent<string>); if (current && payload?.discussion_id === id) apply((previous) => ({ ...previous, utterances: [...previous.utterances, payload.utterance].sort((left, right) => left.sequence - right.sequence) })); }); source.addEventListener("insights.updated", (event) => { const payload = parse<InsightsUpdatedEvent>(event as MessageEvent<string>); if (current && payload?.discussion_id === id) apply((previous) => ({ ...previous, insights: payload.insights })); }); source.addEventListener("discussion.finished", (event) => { const payload = parse<DiscussionFinishedEvent>(event as MessageEvent<string>); if (current && payload?.discussion_id === id) apply((previous) => ({ ...previous, status: payload.status, summary: payload.summary, summary_status: payload.summary_status, finished_at: payload.finished_at })); }); source.addEventListener("discussion.error", (event) => { const payload = parse<DiscussionErrorEvent>(event as MessageEvent<string>); if (current && payload?.discussion_id === id) { setError(payload.error.message); apply((previous) => ({ ...previous, status: payload.final_status, error_code: payload.error.code })); } }); source.onerror = () => { if (current) setConnection("reconnecting"); }; }; setConnection("connecting"); api.getDiscussion(id, controller.signal).then((snapshot) => { if (current && snapshot.id === id) { setDiscussion(snapshot); listen(); } }).catch((reason: unknown) => { if (current && !(reason instanceof DOMException && reason.name === "AbortError")) setError(reason instanceof Error ? reason.message : "讨论加载失败。"); }); return () => { current = false; controller.abort(); source?.close(); }; }, [id]);
  useEffect(() => { reportDiscussion(discussion); return () => reportDiscussion(null); }, [discussion, reportDiscussion]);
  const action = async (operation: () => Promise<void>) => { setPending(true); setError(null); try { await operation(); } catch (reason) { setError(reason instanceof Error ? reason.message : "操作失败，请稍后重试。"); } finally { setPending(false); } };
  if (!discussion) return <main className="page"><p className="error">{error ?? "正在加载讨论…"}</p>{error ? <button className="back" onClick={() => navigate("/")}>← 返回讨论现场</button> : null}</main>;
  const generate = () => action(async () => setDiscussion(await api.generateCast(id))); const confirm = () => action(async () => { const result = await api.confirmDiscussion(id); setDiscussion((previous) => previous ? { ...previous, cast_confirmed: result.cast_confirmed, cast_confirmed_at: result.cast_confirmed_at } : previous); navigate(result.studio_path); }); const start = () => action(async () => { const result = await api.startDiscussion(id); setDiscussion((previous) => previous ? { ...previous, status: result.status, started_at: result.started_at } : previous); }); const stop = () => action(async () => { await api.stopDiscussion(id); }); const retry = () => action(async () => { await api.retrySummary(id); setDiscussion((previous) => previous ? { ...previous, summary_status: "pending" } : previous); }); const showCast = discussion.status === "DRAFT" || (discussion.status === "CAST_READY" && !discussion.cast_confirmed);
  return showCast ? <Cast discussion={discussion} onGenerate={generate} onConfirm={confirm} pending={pending} error={error} /> : <Studio discussion={discussion} connection={connection} onStart={start} onStop={stop} onRetry={retry} pending={pending} error={error} />;
}

export default function App() { const [route, setRoute] = useState(() => parseRoute(window.location.pathname)); const [discussion, setDiscussion] = useState<DiscussionDto | null>(null); const navigate = useCallback((path: string) => { window.history.pushState({}, "", path); setRoute(parseRoute(path)); setDiscussion(null); }, []); useEffect(() => { const popstate = () => { setRoute(parseRoute(window.location.pathname)); setDiscussion(null); }; window.addEventListener("popstate", popstate); return () => window.removeEventListener("popstate", popstate); }, []); return <div className="app"><Header route={route} discussion={discussion} navigate={navigate} />{route.kind === "home" ? <Home navigate={navigate} /> : null}{route.kind === "create" ? <Create navigate={navigate} /> : null}{route.kind === "discussion" ? <DiscussionPage key={route.id} id={route.id} navigate={navigate} reportDiscussion={setDiscussion} /> : null}</div>; }
