import { useEffect, useMemo, useRef, useState, type CSSProperties } from "react";
import { homeDiscussions, participants, studioDiscussion } from "@/mock/discussions";
import type { DiscussionDto, DiscussionStatus, ParticipantDto } from "@/types/contracts";

type View = "home" | "create" | "cast" | "studio";
const labels: Record<DiscussionStatus, string> = { DRAFT: "草稿", CAST_READY: "待开始", RUNNING: "直播中", FINISHED: "已结束", FAILED: "运行异常" };
const Icon = ({ children }: { children: string }) => <span aria-hidden="true">{children}</span>;
function Status({ value }: { value: DiscussionStatus }) { return <span className={`status ${value.toLowerCase()}`}><i />{labels[value]}</span>; }
function Header({ view, go }: { view: View; go: (view: View) => void }) { const title = view === "home" ? "讨论现场" : view === "create" ? "发起一场讨论" : view === "cast" ? "确认嘉宾阵容" : studioDiscussion.topic; return <header className="app-header"><button className="brand" onClick={() => go("home")}><b>AP</b>AI Panel Studio</button><p title={title}>{title}</p><button className="button primary" onClick={() => go("create")}><Icon>＋</Icon>发起讨论</button></header>; }
function Home({ go }: { go: (view: View) => void }) { return <main className="page home"><section className="hero"><small>AI ROUND TABLE · LIVE VIEW</small><h1>让每一个重要问题，<br />都拥有一场值得观看的讨论。</h1><p>邀请不同立场的 AI 专家，在清晰、可追踪的现场中共同拆解一个问题。</p><button className="button primary large" onClick={() => go("create")}>发起一场讨论 <Icon>→</Icon></button></section><section><div className="section-title"><div><small>DISCUSSIONS</small><h2>正在发生的讨论</h2></div><span>共 {homeDiscussions.length} 场</span></div><div className="discussion-grid">{homeDiscussions.map((item) => <article className="discussion-card" key={item.id}><div><Status value={item.status} /><span>{item.expert_count + 1} 位参与者</span></div><h3>{item.topic}</h3><p>最近更新于 今天 {item.status === "RUNNING" ? "16:03" : "15:30"}</p><button className="text-button" onClick={() => go(item.status === "CAST_READY" ? "cast" : "studio")}>{item.status === "RUNNING" ? "进入现场" : item.status === "CAST_READY" ? "查看阵容" : "查看讨论"} <Icon>→</Icon></button></article>)}</div></section></main>; }
function Create({ go }: { go: (view: View) => void }) { const [topic, setTopic] = useState(studioDiscussion.topic); const [count, setCount] = useState(4); const [tried, setTried] = useState(false); const error = tried && !topic.trim(); return <main className="page form-page"><section className="form-card"><small>NEW DISCUSSION</small><h1>从一个值得讨论的问题开始。</h1><p>我们会为你生成一位主持人与 {count} 位立场互补的专家。</p><label htmlFor="topic">讨论话题 <em>必填</em></label><textarea id="topic" value={topic} aria-invalid={error} onBlur={() => setTried(true)} onChange={(e) => setTopic(e.target.value)} />{error && <b className="error">请输入一个讨论话题。</b>}<div className="expert-row"><div><label>专家人数</label><p>不含主持人，可选择 2–8 名。</p></div><div className="stepper"><button disabled={count === 2} onClick={() => setCount(count - 1)} aria-label="减少专家人数">−</button><strong>{count}</strong><button disabled={count === 8} onClick={() => setCount(count + 1)} aria-label="增加专家人数">＋</button></div></div><button className="button primary wide" onClick={() => { setTried(true); if (topic.trim()) go("cast"); }}>生成 AI 阵容 <Icon>→</Icon></button></section></main>; }
function PersonCard({ person, showStatus = false }: { person: ParticipantDto; showStatus?: boolean }) { const state = { idle: "待机", preparing: "准备发言", speaking: "发言中" }[person.runtime_status]; return <article className={`person ${showStatus ? person.runtime_status : ""}`} style={{ "--person": person.color } as CSSProperties}><div className="person-top"><span className="avatar">{person.name[0]}</span><div><small>{person.role === "moderator" ? "主持人" : "专家"}</small><h3>{person.name}</h3><p>{person.profession} · {person.title}</p></div>{showStatus && <span className="runtime"><i />{state}</span>}</div><p className={showStatus ? "focus" : "stance"}>{showStatus ? <><small>公开关注点</small>{person.public_focus ?? "等待讨论推进"}</> : person.stance}</p></article>; }
function Cast({ go }: { go: (view: View) => void }) { return <main className="page cast"><section className="cast-heading"><small>CAST READY</small><h1>{studioDiscussion.topic}</h1><p>已邀请 1 位主持人和 4 位专家。请确认每位嘉宾的公开立场。</p></section><div className="moderator"><PersonCard person={participants[0]} /></div><div className="cast-grid">{participants.slice(1).map((person) => <PersonCard key={person.id} person={person} />)}</div><div className="action-bar"><button className="button quiet">重新生成</button><button className="button primary" onClick={() => go("studio")}>确认阵容并进入演播厅 <Icon>→</Icon></button></div></main>; }
function Transcript({ discussion }: { discussion: DiscussionDto }) { const box = useRef<HTMLDivElement>(null); const [paused, setPaused] = useState(false); const [newCount, setNewCount] = useState(1); const utterances = useMemo(() => [...discussion.utterances].sort((a, b) => a.sequence - b.sequence), [discussion.utterances]); useEffect(() => { if (box.current && !paused) box.current.scrollTop = box.current.scrollHeight; }, [paused]); const scroll = () => { const node = box.current; if (node) setPaused(node.scrollHeight - node.scrollTop - node.clientHeight > 80); }; const latest = () => { box.current?.scrollTo({ top: box.current.scrollHeight, behavior: "smooth" }); setPaused(false); setNewCount(0); }; return <section className="panel transcript"><header><div><small>LIVE TRANSCRIPT</small><h2>现场 Transcript</h2></div><span>{utterances.length} / {discussion.max_public_utterances} 条公开发言</span></header><div className="transcript-scroll" ref={box} onScroll={scroll} aria-live="polite">{utterances.map((utterance) => { const speaker = participants.find((item) => item.id === utterance.participant_id)!; return <article className="utterance" key={utterance.id} style={{ "--person": speaker.color } as CSSProperties}><div><strong>{speaker.name}</strong><span>{speaker.profession} · {speaker.title}</span><time>刚刚</time></div><p>{utterance.content}</p></article>; })}</div>{paused && <button className="new-message" onClick={latest}>有 {newCount || 1} 条新发言 <Icon>↓</Icon></button>}<button className="demo-message" onClick={() => setNewCount(newCount + 1)}>模拟新发言提示</button></section>; }
function Studio({ go }: { go: (view: View) => void }) { const insights = (type: "consensus" | "disagreement") => studioDiscussion.insights.filter((item) => item.type === type); return <main className="studio"><section className="studio-top"><div><p><Status value="RUNNING" /> 实时连接</p><h1>{studioDiscussion.topic}</h1></div><button className="button danger">停止讨论</button></section><div className="studio-grid"><aside className="panel guests"><header><div><small>ON STAGE</small><h2>嘉宾席</h2></div><span>5 位嘉宾</span></header><div className="guest-list">{participants.map((p) => <PersonCard key={p.id} person={p} showStatus />)}</div></aside><Transcript discussion={studioDiscussion} /><aside className="insights">{(["consensus", "disagreement"] as const).map((type) => <section className="panel insight" key={type}><header><div><small>{type === "consensus" ? "CONSENSUS" : "OPEN QUESTIONS"}</small><h2>{type === "consensus" ? "已形成共识" : "关键分歧"}</h2></div></header><ul>{insights(type).map((item) => <li key={item.id}>{item.content}</li>)}</ul></section>)}<section className="summary"><small>IN PROGRESS</small><h2>讨论仍在推进</h2><p>主持人将在观点收束后，给出自然语言总结。</p></section></aside></div><button className="back" onClick={() => go("home")}>← 返回讨论现场</button></main>; }
export default function App() { const [view, go] = useState<View>("home"); return <div className="app"><Header view={view} go={go} />{view === "home" && <Home go={go} />}{view === "create" && <Create go={go} />}{view === "cast" && <Cast go={go} />}{view === "studio" && <Studio go={go} />}</div>; }
